---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: location-server
    tag: v1.0
    service: location-server
  name: location-server-v1.0
spec:
  replicas: 1
  selector:
    matchLabels:
      app: location-server
      tag: v1.0
      service: location-server
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: location-server
        tag: v1.0
        service: location-server
    spec:
      containers:
      - image: sumanbgl1/proj2-location-server:v1.0
        imagePullPolicy: IfNotPresent
        name: location-server-v1.0
        ports:
        - containerPort: 5005
          protocol: TCP
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        env:
          - name: KAFKA_SERVER
            valueFrom:
              configMapKeyRef:
                name: kafka-env
                key: KAFKA_SERVER
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: location-server
    tag: v1.0
    service: location-server
  name: location-server
spec:
  ports:
  - port: 5005
    targetPort: 5005
    nodePort: 6005
  selector:
    app: location-server
    tag: v1.0
    service: location-server
  type: NodePort