# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: app/connection/gRPC/person.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n app/connection/gRPC/person.proto\"Q\n\x06Person\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x12\n\nfirst_name\x18\x02 \x01(\t\x12\x11\n\tlast_name\x18\x03 \x01(\t\x12\x14\n\x0c\x63ompany_name\x18\x04 \x01(\t\"#\n\rPersonRequest\x12\x12\n\nperson_ids\x18\x01 \x03(\x05\"*\n\x0ePersonResponse\x12\x18\n\x07persons\x18\x01 \x03(\x0b\x32\x07.Person2>\n\rPersonService\x12-\n\nGetPersons\x12\x0e.PersonRequest\x1a\x0f.PersonResponseb\x06proto3')



_PERSON = DESCRIPTOR.message_types_by_name['Person']
_PERSONREQUEST = DESCRIPTOR.message_types_by_name['PersonRequest']
_PERSONRESPONSE = DESCRIPTOR.message_types_by_name['PersonResponse']
Person = _reflection.GeneratedProtocolMessageType('Person', (_message.Message,), {
  'DESCRIPTOR' : _PERSON,
  '__module__' : 'app.connection.gRPC.person_pb2'
  # @@protoc_insertion_point(class_scope:Person)
  })
_sym_db.RegisterMessage(Person)

PersonRequest = _reflection.GeneratedProtocolMessageType('PersonRequest', (_message.Message,), {
  'DESCRIPTOR' : _PERSONREQUEST,
  '__module__' : 'app.connection.gRPC.person_pb2'
  # @@protoc_insertion_point(class_scope:PersonRequest)
  })
_sym_db.RegisterMessage(PersonRequest)

PersonResponse = _reflection.GeneratedProtocolMessageType('PersonResponse', (_message.Message,), {
  'DESCRIPTOR' : _PERSONRESPONSE,
  '__module__' : 'app.connection.gRPC.person_pb2'
  # @@protoc_insertion_point(class_scope:PersonResponse)
  })
_sym_db.RegisterMessage(PersonResponse)

_PERSONSERVICE = DESCRIPTOR.services_by_name['PersonService']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _PERSON._serialized_start=36
  _PERSON._serialized_end=117
  _PERSONREQUEST._serialized_start=119
  _PERSONREQUEST._serialized_end=154
  _PERSONRESPONSE._serialized_start=156
  _PERSONRESPONSE._serialized_end=198
  _PERSONSERVICE._serialized_start=200
  _PERSONSERVICE._serialized_end=262
# @@protoc_insertion_point(module_scope)
