  openapi: 3.0.0
  info:
      title: Location API
      description: Newly added delete location API

  paths:
      /api/location:
          delete:
              parameters:
                  - in: path
                    name: location_id
                    required: true
                    schema:
                        type: integer
              responses:
                  '200':
                    description: Sucessfully deleted location object.
                    content:
                      application/json:
                          schema:
                              type: object
                              properties:
                                  id:
                                    type: integer
                                  person_id:
                                      type: integer
                                  latitude:
                                      type: string
                                  longitude:
                                      type: string
                                  creation_time:
                                      type: string

