name: Docker Image Udaconnect app

on:
  push:
    branches: [ "master" ]
#  pull_request:
#    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      #    - name: Build the Docker image
      #      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)

      - name: Docker Login
        # You may pin to the exact commit or the version.
        # uses: docker/login-action@465a07811f14bebb1938fbed4728c6a1ff8901fc
        uses: docker/login-action@v2.2.0
        with:

          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker images
        # You may pin to the exact commit or the version.
        # uses: docker/build-push-action@2eb1c1961a95fc15694676618e422e8ba1d63825
        uses: docker/build-push-action@v4.1.1
        with:
          context: ./modules/frontend
          # Path to the Dockerfile
          file: ./modules/frontend/Dockerfile
          # List of metadata for an image
          #        labels: # optional
          # Load is a shorthand for --output=type=docker

          no-cache: true


          # List of secrets to expose to the build (e.g., key=string, GIT_AUTH_TOKEN=mytoken)
          #        secrets: # optional

          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/nd064-udaconnect-app:${{ github.sha }}
            ${{ secrets.DOCKERHUB_USERNAME }}/nd064-udaconnect-ap:latest

          # optional
          # Sets the target stage to build

